version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        depends_on:
            - mariadb
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "${PORT}:80"
        networks:
            - elastic
    mariadb:
        container_name: mariadb
        image: mariadb:10.5.3-bionic
        ports:
            - "3306:3306"
        networks:
            - elastic
        restart: on-failure
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
            # All scripts in docker-entrypoint-initdb.d/ are automatically
            # executed during container startup
            - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

networks:
  elastic:
    driver: bridge